DROP TABLE IF EXISTS warehouse CASCADE;
CREATE TABLE warehouse (
  W_ID INTEGER DEFAULT '0' NOT NULL,
  W_NAME VARCHAR(10) DEFAULT NULL,
  W_STREET_1 VARCHAR(20) DEFAULT NULL,
  W_STREET_2 VARCHAR(20) DEFAULT NULL,
  W_CITY VARCHAR(20) DEFAULT NULL,
  W_STATE CHAR(2) DEFAULT NULL,
  W_ZIP CHAR(9) DEFAULT NULL,
  W_TAX DECIMAL(4,4) DEFAULT NULL,
  W_YTD DECIMAL(12,2) DEFAULT NULL,
  CONSTRAINT W_PK_ARRAY PRIMARY KEY (W_ID)
);

DROP TABLE IF EXISTS district CASCADE;
CREATE TABLE district (
  D_W_ID INTEGER DEFAULT '0' NOT NULL REFERENCES warehouse (W_ID),
  D_ID INTEGER DEFAULT '0' NOT NULL,
  D_NAME VARCHAR(10) DEFAULT NULL,
  D_STREET_1 VARCHAR(20) DEFAULT NULL,
  D_STREET_2 VARCHAR(20) DEFAULT NULL,
  D_CITY VARCHAR(20) DEFAULT NULL,
  D_STATE CHAR(2) DEFAULT NULL,
  D_ZIP CHAR(9) DEFAULT NULL,
  D_TAX DECIMAL(4,4) DEFAULT NULL,
  D_YTD DECIMAL(12,2) DEFAULT NULL,
  D_NEXT_O_ID INT DEFAULT NULL,
  PRIMARY KEY (D_W_ID,D_ID)
);

DROP TABLE IF EXISTS customer CASCADE;
CREATE TABLE customer (
  C_W_ID INTEGER DEFAULT '0' NOT NULL,
  C_D_ID INTEGER DEFAULT '0' NOT NULL,
  C_ID INTEGER DEFAULT '0' NOT NULL,
  C_FIRST VARCHAR(16) DEFAULT NULL,
  C_MIDDLE CHAR(2) DEFAULT NULL,
  C_LAST VARCHAR(16) DEFAULT NULL,
  C_STREET_1 VARCHAR(20) DEFAULT NULL,
  C_STREET_2 VARCHAR(20) DEFAULT NULL,
  C_CITY VARCHAR(20) DEFAULT NULL,
  C_STATE CHAR(2) DEFAULT NULL,
  C_ZIP CHAR(9) DEFAULT NULL,
  C_PHONE CHAR(16) DEFAULT NULL,
  C_SINCE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  C_CREDIT CHAR(2) DEFAULT NULL,
  C_CREDIT_LIM DECIMAL(12,2) DEFAULT NULL,
  C_DISCOUNT DECIMAL(5,4) DEFAULT NULL,
  C_BALANCE DECIMAL(12,2) DEFAULT NULL,
  C_YTD_PAYMENT FLOAT DEFAULT NULL,
  C_PAYMENT_CNT INTEGER DEFAULT NULL,
  C_DELIVERY_CNT INTEGER DEFAULT NULL,
  C_DATA VARCHAR(500),
  PRIMARY KEY (C_W_ID,C_D_ID,C_ID),
  UNIQUE (C_W_ID,C_D_ID,C_LAST,C_FIRST),
  CONSTRAINT C_FKEY_D FOREIGN KEY (C_D_ID, C_W_ID) REFERENCES district (D_ID, D_W_ID)
);
DROP INDEX IF EXISTS idx_customer;
CREATE INDEX idx_customer ON customer (C_W_ID,C_D_ID,C_LAST);

DROP TABLE IF EXISTS customer_order CASCADE;
CREATE TABLE customer_order (
  O_W_ID INTEGER DEFAULT '0' NOT NULL,
  O_D_ID INTEGER DEFAULT '0' NOT NULL,
  O_ID INTEGER DEFAULT '0' NOT NULL,
  O_C_ID INTEGER DEFAULT NULL,
  O_CARRIER_ID INTEGER DEFAULT NULL,
  O_OL_CNT INTEGER DEFAULT NULL,
  O_ALL_LOCAL INTEGER DEFAULT NULL,
  O_ENTRY_D TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  PRIMARY KEY (O_W_ID,O_D_ID,O_ID),
  UNIQUE (O_W_ID,O_D_ID,O_C_ID,O_ID),
  CONSTRAINT O_FKEY_C FOREIGN KEY (O_C_ID, O_D_ID, O_W_ID) REFERENCES customer (C_ID, C_D_ID, C_W_ID)
);
DROP INDEX IF EXISTS idx_customer_order;
CREATE INDEX idx_customer_order ON customer_order (O_W_ID,O_D_ID,O_C_ID);

CREATE TABLE new_order (
  NO_O_ID INTEGER DEFAULT '0' NOT NULL,
  NO_D_ID INTEGER DEFAULT '0' NOT NULL,
  NO_W_ID SMALLINT DEFAULT '0' NOT NULL,
  CONSTRAINT NO_PK_TREE PRIMARY KEY (NO_D_ID,NO_W_ID,NO_O_ID),
  CONSTRAINT NO_FKEY_O FOREIGN KEY (NO_O_ID, NO_D_ID, NO_W_ID) REFERENCES customer_order (O_ID, O_D_ID, O_W_ID)
);

DROP TABLE IF EXISTS item CASCADE;
CREATE TABLE item (
  I_ID INTEGER DEFAULT '0' NOT NULL,
  I_NAME VARCHAR(24) DEFAULT NULL,
  I_PRICE DECIMAL(5,2) DEFAULT NULL,
  I_IM_ID INTEGER DEFAULT NULL,
  I_DATA VARCHAR(50) DEFAULT NULL,
  CONSTRAINT I_PK_ARRAY PRIMARY KEY (I_ID)
);

DROP TABLE IF EXISTS order_line CASCADE;
CREATE TABLE order_line (
  OL_W_ID INTEGER DEFAULT '0' NOT NULL,
  OL_D_ID INTEGER DEFAULT '0' NOT NULL,
  OL_O_ID INTEGER DEFAULT '0' NOT NULL,
  OL_NUMBER INTEGER DEFAULT '0' NOT NULL,
  OL_I_ID INTEGER DEFAULT NULL,
  OL_DELIVERY_D TIMESTAMP DEFAULT NULL,
  OL_AMOUNT DECIMAL(7,2) DEFAULT NULL,
  OL_SUPPLY_W_ID INTEGER DEFAULT NULL,
  OL_QUANTITY INTEGER DEFAULT NULL,
  OL_DIST_INFO CHAR(24) DEFAULT NULL,
  PRIMARY KEY (OL_W_ID,OL_D_ID,OL_O_ID,OL_NUMBER),
  CONSTRAINT OL_FKEY_O FOREIGN KEY (OL_O_ID, OL_D_ID, OL_W_ID) REFERENCES customer_order (O_ID, O_D_ID, O_W_ID),
  CONSTRAINT OL_FKEY_I FOREIGN KEY (OL_I_ID) REFERENCES item (I_ID)
);
DROP INDEX IF EXISTS idx_order_line_tree;
CREATE INDEX idx_order_line_tree ON order_line (OL_W_ID,OL_D_ID,OL_O_ID);

DROP TABLE IF EXISTS stock CASCADE;
CREATE TABLE stock (
  S_W_ID INTEGER DEFAULT '0' NOT NULL REFERENCES warehouse (W_ID),
  S_I_ID INTEGER DEFAULT '0' NOT NULL REFERENCES item (I_ID),
  S_QUANTITY INTEGER DEFAULT '0' NOT NULL,
  S_YTD INTEGER DEFAULT NULL,
  S_ORDER_CNT INTEGER DEFAULT NULL,
  S_REMOTE_CNT INTEGER DEFAULT NULL,
  S_DIST_01 CHAR(24) DEFAULT NULL,
  S_DIST_02 CHAR(24) DEFAULT NULL,
  S_DIST_03 CHAR(24) DEFAULT NULL,
  S_DIST_04 CHAR(24) DEFAULT NULL,
  S_DIST_05 CHAR(24) DEFAULT NULL,
  S_DIST_06 CHAR(24) DEFAULT NULL,
  S_DIST_07 CHAR(24) DEFAULT NULL,
  S_DIST_08 CHAR(24) DEFAULT NULL,
  S_DIST_09 CHAR(24) DEFAULT NULL,
  S_DIST_10 CHAR(24) DEFAULT NULL,
  S_DATA VARCHAR(24) DEFAULT NULL
  PRIMARY KEY (S_W_ID,S_I_ID)
);

SELECT create_distributed_table('warehouse', 'W_ID');
SELECT create_distributed_table('district', 'D_W_ID');
SELECT create_distributed_table('customer', 'C_W_ID');
SELECT create_distributed_table('customer_order', 'O_W_ID');
SELECT create_reference_table('item');
SELECT create_distributed_table('order_line', 'OL_W_ID');
SELECT create_distributed_table('stock', 'S_W_ID');
